ParkAPI integration
mfdz/OpenTripPlanner pull request #42
Opened 2020-07-13 14:49 UTC by leonardehrenfried

This PR adds an updater that dynamically adds car park using the ParkAPI format.

By default it completely ignores the available spaces in the car park and adds an alert instead.

However, you can also add take them into account and exclude full ones from the search result by setting the request parameter `useCarParkAvailabilityInformation = true`.

2020-07-13 14:50 UTC, leonardehrenfried commented on src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideEdge.java
> +            if(request.useCarParkAvailabilityInformation
Just noticed that this ought to be moved up. Will change it.

2020-07-14 07:35 UTC, hbruch requested changes

2020-07-14 07:35 UTC, hbruch commented on src/main/java/org/opentripplanner/routing/car_park/CarPark.java
> +        return !(Double.isNaN(percentFree)) && percentFree < 0.1;
We should have limits for absolute availability numbers as well, I think. For parkings with less than ten spaces, we should give an alert if only one space is available. More than 20 or 30 parkings IMHO is sufficient if the parking has more than 200 maxCapacity

2020-07-14 15:22 UTC, leonardehrenfried commented on src/main/java/org/opentripplanner/updater/car_park/ParkApiDataSource.java
> +            this.url = url;
No, they don't. This is a straight up copy from the HSL updater.

2020-07-14 15:22 UTC, leonardehrenfried commented on src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
> +            leg.addAlert(Alert.createLowCarParkSpacesAlert(), Locale.ENGLISH);
As discussed, I changed it.

2020-07-16 08:15 UTC, merged